---
- name: email | Creates directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/projects/email/
    state: directory
    mode: "0644"
- name: email | Create docker-compose.yml
  ansible.builtin.copy:
    content: |
      version: "3.4"
      services:
        poste:
          image: analogic/poste.io
          restart: always
          network_mode: "host"
          expose:
            - 25
            - 80
            - 110
            - 143
            - 465
            - 587
            - 993
            - 995
            - 4190
          volumes:
            - /data/mnt/mail:/data
          environment:
            - HTTPS=ON
            - DISABLE_CLAMAV=TRUE
          deploy:
            resources:
              limits:
                cpus: '0.5'
                memory: 512M
    dest: /home/{{ ansible_user }}/projects/email/docker-compose.yml
    mode: "0644"
- name: Email | run email with docker compose
  community.docker.docker_compose:
    project_name: email
    build: "yes"
    project_src: /home/{{ ansible_user }}/projects/email/
    recreate: always
    state: present
