---
- name: prometheus | Clone prometheus-grafana
  when: true
  ansible.builtin.git:
    clone: "yes"
    dest: /home/{{ ansible_user }}/projects/prometheus-grafana
    repo: https://github.com/Al3xDiaz/prometheus-grafana.git
    update: "yes"
    force: "yes"
    version: 011c288
- name: Prometheus | override volumes
  ansible.builtin.copy:
    content: |
      version: '3.8'
      services:
        prometheus:
          volumes:
            - /data/prometheus:/prometheus
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
          user: root
        grafana:
          volumes:
            - /data/grafana-logs:/var/log/grafana
            - /data/grafana-data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
          user: root
    dest: /home/{{ ansible_user }}/projects/prometheus-grafana/docker-compose.override.yml
    mode: "0644"

- name: Prometheus | copy datasources file
  ansible.builtin.copy:
    content: |
      apiVersion: 1
      datasources:
        - name: prometheus
          type: prometheus
          url: https://prometheus.chaoticteam.com
    dest: /home/{{ ansible_user }}/projects/prometheus-grafana/grafana/provisioning/datasources/datasources.yml
    mode: "0644"
    force: "yes"
    follow: "yes"

- name: Prometheus | create env file
  ansible.builtin.copy:
    content: |
      NODE_PORT=9100
      PROM_PORT=9091
      GRAF_PORT=3001
    dest: /home/{{ ansible_user }}/projects/prometheus-grafana/.env
    mode: "0644"

- name: Prometheus | run prometheus-grafana with docker compose
  register: output
  community.docker.docker_compose:
    build: "yes"
    project_name: prometheus-grafana
    project_src: /home/{{ ansible_user }}/projects/prometheus-grafana/
    recreate: always
    state: present
