
image: 
  name: hashicorp/terraform
  entrypoint: ['']
services:
  - hashicorp/terraform:light

stages:
  - init-validate
  - apply
  - destroy

variables:
  SECURE_FILES_DOWNLOAD_PATH: 'terraform'
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  TF_VAR_id_private_key_path: ".ssh/id_$USER"
  TF_VAR_id_public_key_path: ".ssh/id_$USER.pub"
before_script:
  - cd terraform/
  - mkdir -p ~/.ssh
  - cp $id_private_key ~/.ssh/id_$USER
  - cp $id_public_key ~/.ssh/id_$USER.pub
init:
  stage: init-validate  
  cache:
    key: build_cache
    paths:
     - terraform/.terraform
     - terraform/.terraform.lock.hcl
     - terraform/.terraform.tfstate
     - terraform/.terraform.tfstate.backup
     - terraform/gitlab.auto.tfvars
     - home/
  script:
    - terraform init
    - terraform validate

apply:
  stage: apply
  cache:
    key: build_cache
    paths:
     - terraform/.terraform
     - terraform/.terraform.lock.hcl
     - terraform/.terraform.tfstate
     - terraform/.terraform.tfstate.backup
     - terraform/gitlab.auto.tfvars
     - home/
  script:
    - terraform apply -auto-approve
  only:
    - main
  environment: production

destroy:
  stage: destroy
  cache:
    key: build_cache
    paths:
     - terraform/.terraform
     - terraform/.terraform.lock.hcl
     - terraform/.terraform.tfstate
     - terraform/.terraform.tfstate.backup
     - terraform/gitlab.auto.tfvars
     - home/
  when: manual
  script:
    - terraform destroy -auto-approve
  only:
    - main
  environment: production