image: docker:20.10.16
services:
  - docker:20.10.16-dind

stages:
  - init
  - validate
  - plan
  - apply

variables:
  GITLAB_AUTO_TFVARS: $GITLAB_AUTO_TFVARS
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

init:
  stage: init
  cache:
    key: build-cache
    paths:
     - terraform/
     - home/

  script:
    - echo "$GITLAB_AUTO_TFVARS" > terraform/gitlab.auto.tfvars
    - docker-compose run --rm --entrypoint /root/terraform/terraform-init.sh terraform

validate:
  stage: validate
  cache:
    key: build-cache
    paths:
     - terraform/
     - home/

  script:
    - ls -la terraform/
    - docker-compose run --rm  --entrypoint terraform terraform validate

plan:
  stage: plan
  cache:
    key: build-cache
    paths:
     - terraform/
     - home/

  script:
    - docker-compose run --rm  --entrypoint terraform terraform plan
  only:
    - main

apply:
  stage: apply
  cache:
    key: build-cache
    paths:
     - terraform/
     - home/

  script:
    - docker-compose run --rm  --entrypoint terraform terraform apply -auto-approve
  only:
    - main
  environment: production