image: docker:20.10.16
services:
  - docker:20.10.16-dind

stages:
  - init
  - validate
  - plan
  - apply

variables:
  GITLAB_AUTO_TFVARS: $GITLAB_AUTO_TFVARS
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

init:
  stage: init
  script:
    - echo "$GITLAB_AUTO_TFVARS" > terraform/gitlab.auto.tfvars
    - docker-compose run --rm --entrypoint terraform terraform init \
      -backend-config="address=https://gitlab.com/api/v4/projects/42073065/terraform/state/old-state-name" \
      -backend-config="lock_address=https://gitlab.com/api/v4/projects/42073065/terraform/state/old-state-name/lock" \
      -backend-config="unlock_address=https://gitlab.com/api/v4/projects/42073065/terraform/state/old-state-name/lock" \
      -backend-config="username=Al3xDiaz" \
      -backend-config="password=$GITLAB_ACCESS_TOKEN" \
      -backend-config="lock_method=POST" \
      -backend-config="unlock_method=DELETE" \
      -backend-config="retry_wait_min=5"

validate:
  stage: validate
  script:
    - docker-compose run --rm  --entrypoint terraform terraform validate

plan:
  stage: plan
  script:
    - docker-compose run --rm  --entrypoint terraform terraform plan
  only:
    - main

apply:
  stage: apply
  script:
    - docker-compose run --rm  --entrypoint terraform terraform apply -auto-approve
  only:
    - main
  environment: production