---
apply:
  cache:
    key: build_cache
    paths:
      - cd terraform/
      - terraform/.terraform
      - terraform/.terraform.lock.hcl
      - terraform/.terraform.tfstate
      - terraform/.terraform.tfstate.backup
      - terraform/gitlab.auto.tfvars
      - terraform/terraform_output.txt
      - home/
  environment: production
  only:
    - main
  script:
    # - terraform apply -auto-approve
    - terraform plan 
    - terraform output -raw servers > terraform/terraform_output.txt
  stage: apply
before_script:
  - mkdir -p ~/.ssh
  - cp $id_private_key ~/.ssh/ansible
  - cp $id_public_key ~/.ssh/anisble.pub
config_infrastructure:
  environment: production
  only:
    - main
  script:
    - cp terraform/terraform_output.txt ansible/inventory
    - cd ansible/
    - ansible-playbook main.yml
  variables:
    ANSIBLE_PIPELINING: 'true'
  stage: config_infrastructure
destroy:
  cache:
    key: build_cache
    paths:
      - cd terraform/
      - terraform/.terraform
      - terraform/.terraform.lock.hcl
      - terraform/.terraform.tfstate
      - terraform/.terraform.tfstate.backup
      - terraform/gitlab.auto.tfvars
      - home/
  environment: production
  only:
    - main
  script:
    - terraform destroy -auto-approve
  stage: destroy
  when: manual
image:
  entrypoint: ['']
  name: hashicorp/terraform
init:
  cache:
    key: build_cache
    paths:
      - cd terraform/
      - terraform/.terraform
      - terraform/.terraform.lock.hcl
      - terraform/.terraform.tfstate
      - terraform/.terraform.tfstate.backup
      - terraform/gitlab.auto.tfvars
      - home/
  script:
    - terraform init
    - terraform validate
  stage: init-validate
services:
  - hashicorp/terraform:light
stages:
  - init-validate
  - apply
  - destroy
  - config_infrastructure
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  SECURE_FILES_DOWNLOAD_PATH: terraform
  TF_VAR_id_private_key_path: .ssh/id_$USER
  TF_VAR_id_public_key_path: .ssh/id_$USER.pub