version: '3.9'
services:
  terraform:
    image: hashicorp/terraform
    environment:
      USER: ${USER}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

      TF_VAR_settings_domains: ${SETTINGS_DOMAINS}
    user: root
    volumes:
      -  ~/.ssh:/root/.ssh
      - ./terraform:/root/terraform/
    working_dir: /root/terraform/
    entrypoint: "/root/terraform/entrypoint.sh"
    command: ["init"]
    