version: '3.9'
services:
  terraform:
    image: hashicorp/terraform
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    user: root
    volumes:
      - ./home/:/root/
      - ./terraform:/root/terraform
    working_dir: /root/terraform/
    entrypoint: ["/root/entrypoint.sh"]
    command: ["terraform", "init"]
    tty: true
    