---
services:
  ansible:
    command: ["ansible-playbook","-i", "inventory", "main.yml"]
    environment:
      ANSIBLE_INVENTORY: ./inventory
    image: registry.gitlab.com/chaoticteams/ansible
    volumes:
      - ~/.ssh/:/home/user_keys
      - ./ansible:/root/
      - /root/.ssh
      - /root/.ansible
    working_dir: /root/
  terraform:
    command: ["init"]
    entrypoint: /root/terraform/entrypoint.sh
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      USER: ${USER}
    image: hashicorp/terraform
    user: root
    volumes:
      - ~/.ssh:/root/.ssh
      - ./terraform:/root/terraform/
    working_dir: /root/terraform/
version: '3.9'
volumes:
  ansible_home: null