---
- file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  name: remove default nginx
- loop: "{{ items }}"
  name: config nginx
  notify: restart nginx
  template:
    dest: /etc/nginx/sites-available/{{item.domain}}
    src: nginx.conf.j2
- file:
    dest: /etc/nginx/sites-enabled/{{item.domain}}
    src: /etc/nginx/sites-available/{{item.domain}}
    state: link
  loop: "{{ items }}"
  name: enable nginx
  notify: restart nginx