---
- name: Docker | update packages using apt
  ansible.builtin.apt:
    cache_valid_time: 3600
    force_apt_get: true
    update_cache: true
- name: Docker | docker dependencies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - gnupg
    state: present
    update_cache: "yes"

- name: "01docker | Add Docker`s official GPG key"
  ansible.builtin.apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg

- name: "01docker | Add Docker Repository"
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

  register: docker
# Desciption of the Ansible playbook
- name: "01docker | Update apt and install docker-ce"
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: "yes"

- name: "01docker | Install Docker Module for Python"
  ansible.builtin.pip:
    name: docker==6.1.3
