---
- name: "02docker-compose | Install Docker Compose"
  ansible.builtin.pip:
    name: docker-compose
- name: "02docker-compose | Install docker compose"
  ansible.builtin.get_url:
    dest: /usr/bin/docker-compose
    group: docker
    mode: u=rwx,g=rx,o=rx
    url: "{{ file_url }}{{ file_path }}"
