---
- include_tasks: 01docker.yml
  name: Install Docker
  vars:
    file_path: /compose/releases/download/1.29.2/docker-compose-linux-x86_64
    file_url: https://github.com/docker
  when:
    - ansible_os_family == 'Debian'
- include_tasks: 02docker-compose.yml
  name: Install Docker Compose
  vars:
    file_path: /compose/releases/download/1.29.2/docker-compose-linux-x86_64
    file_url: https://github.com/docker
  when:
    - ansible_os_family == 'Debian'
- name: add user to docker group
  user:
    append: 'yes'
    groups: docker
    name: "{{ ansible_user }}"
  when:
    - ansible_os_family == 'Debian'