alias ping="ansible all --key-file ssh-keys/ansible -m ping"
alias playbook="ansible-playbook --key-file ssh-keys/ansible"
alias hosts="ansible all --list-hosts"

alias devopsPlaybook="playbook playbooks/devopsPlaybook.yml --ask-become-pass --tags"
alias devtools="playbook playbooks/devtools.yml --ask-become-pass --tags"
alias htopPlaybook="playbook playbooks/htopPlaybook.yml --ask-become-pass --tags"
alias interpreters="playbook playbooks/interpreters.yml --ask-become-pass --tags"
alias k8_master_node="playbook playbooks/k8-master-node.yml --ask-become-pass --tags"
alias k8_nodes="playbook playbooks/k8-nodes.yml --ask-become-pass --tags"
alias k8_workers_node="playbook playbooks/k8-workers-node.yml --ask-become-pass --tags"
alias nginx="playbook playbooks/nginx.yml --ask-become-pass --tags"
